Data: 
- users.csv
- movies.csv
- ratings_new.csv

In [ ]:
# they want to find similar friends
# if they like A, you'll like A

In [1]:
import pandas as pd
import numpy as np

# Load the u.user file into a dataframe
# u_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']

users = pd.read_csv('users.csv')
users.head()

user_id  age sex  occupation zip_code
0        1   24   M  technician    85711
1        2   53   F       other    94043
2        3   23   M      writer    32067
3        4   24   M  technician    43537
4        5   33   F       other    15213

In [2]:
# Load the u.item file into a dataframe
# i_cols = ['movie_id', 'title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
#  'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
#  'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

movies = pd.read_csv('movies.csv')
pd.set_option('display.max_columns', None)
movies.head()

movie_id              title release date  video release date  \
0         1   Toy Story (1995)     1-Jan-95                 NaN   
1         2   GoldenEye (1995)     1-Jan-95                 NaN   
2         3  Four Rooms (1995)     1-Jan-95                 NaN   
3         4  Get Shorty (1995)     1-Jan-95                 NaN   
4         5     Copycat (1995)     1-Jan-95                 NaN   

                                            IMDb URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0   
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1   
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0   
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1   
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0   

   Adventure  Animation  Children\  Comedy  Crime  Documentary  Drama  \
0          0          1          1       1      0            0      0   
1          1          0          0       0      0            0      0   
2          0          0          0       0      0            0      0   
3          0          0          0       1      0            0      1   
4          0          0          0       0      1            0      1   

   Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  \
0        0          0       0        0        0        0       0         0   
1        0          0       0        0        0        0       0         1   
2        0          0       0        0        0        0       0         1   
3        0          0       0        0        0        0       0         0   
4        0          0       0        0        0        0       0         1   

   War  Western  
0    0        0  
1    0        0  
2    0        0  
3    0        0  
4    0        0

In [3]:
# Remove all information except Movie ID and title
movies = movies[['movie_id', 'title']]
movies.head()

movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [4]:
# Load the u.data file into a dataframe
# r_cols = ['user_id', 'movie_id', 'rating', 'timestamp']

ratings = pd.read_csv('ratings_new.csv')
ratings.head()

user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [5]:
ratings.describe()

user_id       movie_id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [6]:
# Drop the timestamp column
ratings = ratings.drop('timestamp', axis=1)

In [7]:
ratings.shape

(100000, 3)

In [8]:
# Import the train_test_split function
from sklearn.model_selection import train_test_split

# Assign X as the original ratings dataframe and y as the user_id column of ratings.
X = ratings.copy()
y = ratings['user_id']

# Split into training and test datasets, stratified along user_id
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, stratify=y, random_state=42)

In [9]:
# Import the mean_squared_error function
from sklearn.metrics import mean_squared_error

# Function that computes the root mean squared error (or RMSE)
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [11]:
# Function to compute the RMSE score obtained on the testing set by a model
def score(cf_model):
    
    # Construct a list of user-movie tuples from the testing dataset
    id_pairs = zip(X_test['user_id'], X_test['movie_id'])
    
    # Predict the rating for every user-movie tuple
    y_pred = np.array([cf_model(user, movie) for (user, movie) in id_pairs])
    
    # Extract the actual ratings given by the users in the test data
    y_true = np.array(X_test['rating'])
    print(y_true)
    print(y_pred)
    
    # Return the final RMSE score
    return rmse(y_true, y_pred)

In [14]:
# Build the ratings matrix using pivot_table function
r_matrix = X_train.pivot_table(values='rating', index='user_id', columns='movie_id')
r_matrix.head()

movie_id  1     2     3     4     5     6     7     8     9     10    11    \
user_id                                                                      
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0   2.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   
5          NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  12    13    14    15    16    17    18    19    20    21    22    \
user_id                                                                      
1          5.0   NaN   5.0   NaN   NaN   NaN   4.0   5.0   4.0   1.0   NaN   
2          NaN   4.0   4.0   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   3.0   NaN   

movie_id  23    24    25    26    27    28    29    30    31    32    33    \
user_id                                                                      
1          4.0   3.0   4.0   3.0   NaN   4.0   1.0   NaN   3.0   5.0   4.0   
2          NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   4.0   3.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   

movie_id  34    35    36    37    38    39    40    41    42    43    44    \
user_id                                                                      
1          NaN   1.0   2.0   NaN   3.0   4.0   NaN   2.0   NaN   4.0   5.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   

movie_id  45    46    47    48    49    50    51    52    53    54    55    \
user_id                                                                      
1          NaN   4.0   4.0   5.0   3.0   5.0   NaN   4.0   3.0   3.0   5.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  56    57    58    59    60    61    62    63    64    65    66    \
user_id                                                                      
1          4.0   NaN   4.0   5.0   NaN   NaN   3.0   2.0   5.0   4.0   4.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   NaN   NaN   NaN   

movie_id  67    68    69    70    71    72    73    74    75    76    77    \
user_id                                                                      
1          NaN   4.0   3.0   3.0   3.0   4.0   3.0   1.0   NaN   4.0   NaN   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  78    79    80    81    82    83    84    85    86    87    88    \
user_id                                                                      
1          1.0 

# Baseline

In [10]:
# Define the baseline model to always return 3
def baseline(user_id, movie_id):
    return 3.0

In [37]:
# user 2, movie 12
baseline(2,12)

3.0

In [12]:
# RMSE
score(baseline)

[4 2 3 ... 1 4 2]
[3. 3. 3. ... 3. 3. 3.]


1.2470926188539486

# User-Based Collaborative Filtering
## Mean

In [15]:
# User Based Collaborative Filter using Mean Ratings
def cf_user_mean(user_id, movie_id):
    
    # Check if movie_id exists in r_matrix
    if movie_id in r_matrix:
        
        # Compute the mean of all the ratings given to the movie
        mean_rating = r_matrix[movie_id].mean()
    else:
        
        # Default to a rating of 3.0 in the absence of any information
        mean_rating = 3.0  
    return mean_rating

In [27]:
# user 2, movie 12
cf_user_mean(2,12)

4.409326424870466

In [16]:
# RMSE
score(cf_user_mean)

[4 2 3 ... 1 4 2]
[4.         3.98058252 3.68571429 ... 3.71071429 3.90338164 3.        ]


1.0234701463131335

## Weighted Mean

In [17]:
r_matrix.head()

movie_id  1     2     3     4     5     6     7     8     9     10    11    \
user_id                                                                      
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0   2.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   
5          NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  12    13    14    15    16    17    18    19    20    21    22    \
user_id                                                                      
1          5.0   NaN   5.0   NaN   NaN   NaN   4.0   5.0   4.0   1.0   NaN   
2          NaN   4.0   4.0   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   3.0   NaN   

movie_id  23    24    25    26    27    28    29    30    31    32    33    \
user_id                                                                      
1          4.0   3.0   4.0   3.0   NaN   4.0   1.0   NaN   3.0   5.0   4.0   
2          NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   4.0   3.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   

movie_id  34    35    36    37    38    39    40    41    42    43    44    \
user_id                                                                      
1          NaN   1.0   2.0   NaN   3.0   4.0   NaN   2.0   NaN   4.0   5.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   

movie_id  45    46    47    48    49    50    51    52    53    54    55    \
user_id                                                                      
1          NaN   4.0   4.0   5.0   3.0   5.0   NaN   4.0   3.0   3.0   5.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  56    57    58    59    60    61    62    63    64    65    66    \
user_id                                                                      
1          4.0   NaN   4.0   5.0   NaN   NaN   3.0   2.0   5.0   4.0   4.0   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   NaN   NaN   NaN   

movie_id  67    68    69    70    71    72    73    74    75    76    77    \
user_id                                                                      
1          NaN   4.0   3.0   3.0   3.0   4.0   3.0   1.0   NaN   4.0   NaN   
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5          NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

movie_id  78    79    80    81    82    83    84    85    86    87    88    \
user_id                                                                      
1          1.0 

In [18]:
# Create a dummy ratings matrix with all null values imputed to 0
r_matrix_dummy = r_matrix.copy().fillna(0)
r_matrix_dummy.head()

movie_id  1     2     3     4     5     6     7     8     9     10    11    \
user_id                                                                      
1          5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0   2.0   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   
5          0.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

movie_id  12    13    14    15    16    17    18    19    20    21    22    \
user_id                                                                      
1          5.0   0.0   5.0   0.0   0.0   0.0   4.0   5.0   4.0   1.0   0.0   
2          0.0   4.0   4.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0   3.0   0.0   

movie_id  23    24    25    26    27    28    29    30    31    32    33    \
user_id                                                                      
1          4.0   3.0   4.0   3.0   0.0   4.0   1.0   0.0   3.0   5.0   4.0   
2          0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   4.0   3.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   

movie_id  34    35    36    37    38    39    40    41    42    43    44    \
user_id                                                                      
1          0.0   1.0   2.0   0.0   3.0   4.0   0.0   2.0   0.0   4.0   5.0   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   0.0   

movie_id  45    46    47    48    49    50    51    52    53    54    55    \
user_id                                                                      
1          0.0   4.0   4.0   5.0   3.0   5.0   0.0   4.0   3.0   3.0   5.0   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

movie_id  56    57    58    59    60    61    62    63    64    65    66    \
user_id                                                                      
1          4.0   0.0   4.0   5.0   0.0   0.0   3.0   2.0   5.0   4.0   4.0   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   

movie_id  67    68    69    70    71    72    73    74    75    76    77    \
user_id                                                                      
1          0.0   4.0   3.0   3.0   3.0   4.0   3.0   1.0   0.0   4.0   0.0   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

movie_id  78    79    80    81    82    83    84    85    86    87    88    \
user_id                                                                      
1          1.0 

In [19]:
# Import cosine_score 
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix using the dummy ratings matrix
cosine_sim = cosine_similarity(r_matrix_dummy, r_matrix_dummy)

In [20]:
# Convert into pandas dataframe 
cosine_sim = pd.DataFrame(cosine_sim, index=r_matrix.index, columns=r_matrix.index)
cosine_sim.head()

user_id       1         2         3         4         5         6         7    \
user_id                                                                         
1        1.000000  0.118076  0.029097  0.011628  0.264677  0.312419  0.308729   
2        0.118076  1.000000  0.099097  0.107680  0.034279  0.152789  0.086705   
3        0.029097  0.099097  1.000000  0.252131  0.026893  0.062539  0.039767   
4        0.011628  0.107680  0.252131  1.000000  0.000000  0.045543  0.078812   
5        0.264677  0.034279  0.026893  0.000000  1.000000  0.202843  0.299619   

user_id       8         9         10        11        12        13        14   \
user_id                                                                         
1        0.224269  0.026017  0.286411  0.220437  0.213117  0.351204  0.235971   
2        0.078864  0.068940  0.092399  0.098726  0.074706  0.143962  0.088732   
3        0.089474  0.078162  0.037670  0.031866  0.086560  0.138187  0.040749   
4        0.095354  0.059498  0.053879  0.074209  0.038437  0.060181  0.034741   
5        0.163724  0.038474  0.153021  0.290192  0.101406  0.298501  0.203679   

user_id       15        16        17        18        19        20        21   \
user_id                                                                         
1        0.138522  0.341201  0.136597  0.340766  0.088945  0.168888  0.168084   
2        0.352885  0.067225  0.141859  0.111234  0.085395  0.023666  0.117823   
3        0.098841  0.057337  0.006849  0.027751  0.000000  0.039608  0.114870   
4        0.107286  0.059952  0.000000  0.014787  0.044219  0.031658  0.085692   
5        0.090818  0.198008  0.024542  0.211799  0.123906  0.163770  0.138529   

user_id       22        23        24        25        26        27        28   \
user_id                                                                         
1        0.245544  0.363621  0.244380  0.266342  0.184639  0.142040  0.218228   
2        0.043818  0.085681  0.142768  0.082198  0.415777  0.108961  0.039521   
3        0.027501  0.022252  0.044016  0.000000  0.115385  0.006513  0.013229   
4        0.014654  0.022396  0.142399  0.026656  0.068105  0.041645  0.089874   
5        0.310043  0.322358  0.105729  0.182711  0.093950  0.052063  0.275308   

user_id       29        30        31        32        33        34        35   \
user_id                                                                         
1        0.050924  0.149212  0.091746  0.129824  0.038110  0.011462  0.016556   
2        0.196305  0.183749  0.052282  0.159113  0.083984  0.071035  0.070759   
3        0.136596  0.063315  0.154689  0.071696  0.319455  0.095315  0.201552   
4        0.182678  0.048197  0.037467  0.084593  0.228098  0.206432  0.167468   
5        0.000000  0.102223  0.028427  0.111519  0.000000  0.003390  0.000000   

user_id       36        37        38        39        40        41        42   \
user_id                                                                         
1        0.000000  0.153244  0.148866  0.030900  0.038933  0.290524  0.327108   
2        0.041877  0.071331  0.050981  0.190476  0.171597  0.034932  0.076522   
3        0.067167  0.000000  0.053754  0.168958  0.296983  0.031889  0.030219   
4        0.080916  0.034698  0.069562  0.186854  0.142598  0.033985  0.046006   
5        0.000000  0.146963  0.184862  0.000000  0.003598  0.182397  0.282618   

user_id       43        44        45        46        47        48        49   \
user_id                                                                         
1        0.298265  0.396955  0.163744  0.084690  0.000000  0.160882  0.233123   
2        0.219074  0.079185  0.287860  0.199487  0.221050  0.058247  0.091349   
3        0.113582  0.039758  0.034619  0.170377  0.247634  0.049931  0.093332   
4        0.095562  0.063556  0.027670  0.123799  0.263906  0.000000  0.034102   
5        0.224105  0.302753  0.106161  0.056926  0.000000  0.146481  0.247712   

user_id       50        

In [21]:
# User Based Collaborative Filter using Weighted Mean Ratings
def cf_user_wmean(user_id, movie_id):
    
    # Check if movie_id exists in r_matrix
    if movie_id in r_matrix:
        
        # Get the similarity scores for the user in question with every other user
        sim_scores = cosine_sim[user_id]
        
        # Get the user ratings for the movie in question
        m_ratings = r_matrix[movie_id]
        
        # Extract the indices containing NaN in the m_ratings series
        idx = m_ratings[m_ratings.isnull()].index
        
        # Drop the NaN values from the m_ratings Series
        m_ratings = m_ratings.dropna()
        
        # Drop the corresponding cosine scores from the sim_scores series
        sim_scores = sim_scores.drop(idx)
        
        # Compute the final weighted mean
        wmean_rating = np.dot(sim_scores, m_ratings) / sim_scores.sum()
    
    else:
        # Default to a rating of 3.0 in the absence of any information
        wmean_rating = 3.0
    
    # pd.DataFrame(wmean_rating).to_csv('Data/wmean_rating.csv')
    return wmean_rating

In [28]:
# user 2, movie 12
cf_user_wmean(2,12)

4.399787171879637

In [23]:
# RMSE
score(cf_user_wmean)

[4 2 3 ... 1 4 2]
[4.0019218  3.93798639 3.81311742 ... 3.67256243 3.88113487 2.83484213]


1.0174483808407588

## Demographics

In [24]:
# Merge the original users dataframe with the training set 
merged_df = pd.merge(X_train, users)
merged_df.head()

user_id  movie_id  rating  age sex  occupation zip_code
0      889       684       2   24   M  technician    78704
1      889       279       2   24   M  technician    78704
2      889        29       3   24   M  technician    78704
3      889       190       3   24   M  technician    78704
4      889       232       3   24   M  technician    78704

In [25]:
# Compute the mean rating of every movie by gender
# 每个movie每个gender的rating mean
gender_mean = merged_df[['movie_id', 'sex', 'rating']].groupby(['movie_id', 'sex'])['rating'].mean()
gender_mean

movie_id  sex
1         F      3.827586
          M      3.918919
2         F      3.230769
          M      3.228916
3         F      2.785714
                   ...   
1675      M      3.000000
1676      M      2.000000
1679      M      3.000000
1681      M      3.000000
1682      M      3.000000
Name: rating, Length: 3048, dtype: float64

In [26]:
# Set the index of the users dataframe to the user_id
users = users.set_index('user_id')
users.head()

age sex  occupation zip_code
user_id                              
1         24   M  technician    85711
2         53   F       other    94043
3         23   M      writer    32067
4         24   M  technician    43537
5         33   F       other    15213

### Gender

In [29]:
# Gender Based Collaborative Filter using Mean Ratings
def cf_gender(user_id, movie_id):
    
    # Check if movie_id exists in r_matrix (or training set)
    if movie_id in r_matrix:
        
        # Identify the gender of the user
        gender = users.loc[user_id]['sex']
        
        # Check if the gender has rated the movie
        if gender in gender_mean[movie_id]:
            
            # Compute the mean rating given by that gender to the movie
            gender_rating = gender_mean[movie_id][gender] 
            
        else:
            gender_rating = 3.0
    else:
        
        # Default to a rating of 3.0 in the absence of any information
        gender_rating = 3.0
        
    return gender_rating

In [30]:
# user 2, movie 12
cf_gender(2,12)

4.472222222222222

In [31]:
# RMSE
score(cf_gender)

[4 2 3 ... 1 4 2]
[3.96296296 3.31818182 3.71794872 ... 3.85714286 3.90853659 3.        ]


1.0330308800874282

In [32]:
# Compute the mean rating by gender and occupation
gen_occ_mean = merged_df[['sex', 'rating', 'movie_id', 'occupation']].pivot_table(
    values='rating', index='movie_id', columns=['occupation', 'sex'], aggfunc='mean')

gen_occ_mean.head()

occupation administrator           artist              doctor educator  \
sex                    F         M      F         M         M        F   
movie_id                                                                 
1                    4.0  4.222222   4.25  3.500000  3.666667     3.50   
2                    3.0  3.750000    NaN       NaN       NaN      NaN   
3                    3.5  2.500000    NaN       NaN       NaN     4.00   
4                    3.0  3.888889    NaN  4.666667  3.000000     2.75   
5                    4.0  2.333333    NaN       NaN       NaN     4.00   

occupation           engineer           entertainment           executive  \
sex                M        F         M             F         M         F   
movie_id                                                                    
1           3.923077      4.0  3.970588           5.0  3.222222       3.0   
2           3.250000      NaN  3.363636           NaN  3.000000       NaN   
3           2.500000      NaN  3.625000           NaN       NaN       NaN   
4           3.636364      NaN  3.555556           NaN  4.000000       NaN   
5           1.500000      NaN  2.666667           NaN  3.250000       NaN   

occupation           healthcare      homemaker     lawyer           librarian  \
sex                M          F    M         F   M      F         M         F   
movie_id                                                                        
1           4.066667   2.250000  4.0       NaN NaN    NaN  4.166667      4.00   
2           3.000000   2.666667  NaN       NaN NaN    NaN  5.000000      3.00   
3           2.000000        NaN  NaN       NaN NaN    NaN       NaN      2.50   
4           3.400000   3.000000  NaN       NaN NaN    NaN  4.500000      3.60   
5           4.500000   3.000000  NaN       NaN NaN    NaN       NaN      3.25   

occupation           marketing       none          other           programmer  \
sex                M         F     M    F    M         F         M          F   
movie_id                                                                        
1           3.571429       4.0  4.25  3.5  5.0  4.000000  4.107143        4.0   
2                NaN       NaN  3.00  5.0  4.0  3.666667  3.500000        NaN   
3                NaN       NaN  2.00  1.0  5.0  3.500000  3.250000        NaN   
4           3.000000       NaN  3.50  5.0  2.0  3.750000  2.888889        3.0   
5           4.000000       NaN  3.00  5.0  4.0  4.333333  3.600000        NaN   

occupation           retired           salesman           scientist            \
sex                M       F         M        F         M         F         M   
movie_id                                                                        
1           4.280000     NaN  3.666667      4.0  4.000000       3.5  3.888889   
2           3.000000     NaN  2.000000      NaN       NaN       NaN       NaN   
3           2.600000     NaN       NaN      NaN  1.000000       NaN       NaN   
4           3.615385     4.0  4.000000      4.0  3.666667       NaN  3.600000   
5           3.285714     NaN  3.500000      NaN       NaN       NaN  3.500000   

occupation   student           technician              writer            
sex                F         M          F         M         F         M  
movie_id                                                                 
1           3.833333  3.709091        4.0  4.200000  4.166667  3.142857  
2           2.333333  3.333333        NaN  2.714286  5.000000  2.666667  
3           2.000000  3.217391        NaN  4.000000       NaN  1.000000  
4           3.285714  3.724138        NaN  3.200000  4.250000  3.500000  
5           4.333333  3.272727        NaN  3.333333  4.000000  2.666667

In [86]:
# pd.DataFrame(gen_occ_mean).to_csv('data/gen_occ_mean.csv', index=True)

### Gender and Occupation

In [33]:
# Gender and Occupation Based Collaborative Filter using Mean Ratings
def cf_gen_occ(user_id, movie_id):
    
    # Check if movie_id exists in gen_occ_mean
    if movie_id in gen_occ_mean.index:
        
        # Identify the user
        user = users.loc[user_id]
        
        # Identify the gender and occupation
        gender = user['sex']
        occ = user['occupation']
        
        # Check if the occupation has rated the movie
        if occ in gen_occ_mean.loc[movie_id]:
            
            # Check if the gender has rated the movie
            if gender in gen_occ_mean.loc[movie_id][occ]:
                
                # Extract the required rating
                rating = gen_occ_mean.loc[movie_id][occ][gender]
                
                # Default to 3.0 if the rating is null
                if np.isnan(rating):
                    rating = 3.0
                
                return rating
            
    # Return the default rating    
    return 3.0

In [34]:
# user 2, movie 12
cf_gen_occ(2,12)

4.5

In [35]:
# RMSE
score(cf_gen_occ)

[4 2 3 ... 1 4 2]
[3.         4.         3.6        ... 4.05555556 3.77777778 3.        ]


1.1391976012043645

In [36]:
print('baseline:',score(baseline))
print()
print('cf_user_mean:',score(cf_user_mean))
print()
print('cf_user_wmean:',score(cf_user_wmean))
print()
print('cf_gender:',score(cf_gender))
print()
print('cf_gen_occ:',score(cf_gen_occ))

[4 2 3 ... 1 4 2]
[3. 3. 3. ... 3. 3. 3.]
baseline: 1.2470926188539486

[4 2 3 ... 1 4 2]
[4.         3.98058252 3.68571429 ... 3.71071429 3.90338164 3.        ]
cf_user_mean: 1.0234701463131335

[4 2 3 ... 1 4 2]
[4.0019218  3.93798639 3.81311742 ... 3.67256243 3.88113487 2.83484213]
cf_user_wmean: 1.0174483808407588

[4 2 3 ... 1 4 2]
[3.96296296 3.31818182 3.71794872 ... 3.85714286 3.90853659 3.        ]
cf_gender: 1.0330308800874282

[4 2 3 ... 1 4 2]
[3.         4.         3.6        ... 4.05555556 3.77777778 3.        ]
cf_gen_occ: 1.1391976012043645
